version = 0.1
[default.deploy.parameters]
stack_name = "CryptoCyberNewsFastAPI"
resolve_s3 = true
s3_prefix = "CryptoCyberNewsFastAPI"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
