AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI deployment to AWS Lambda

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CryptoCyberNewsFastAPI
      Handler: app.main.handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          NEWS_API_KEY: !Ref NewsApiKey
          AUTH_API_KEY: !Ref AuthApiKey

Parameters:
  NewsApiKey:
    Type: String
    Description: "News API Key for fetching crypto news"
  AuthApiKey:
    Type: String
    Description: "API Key for authentication"
