AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FastAPILambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CryptoCyberNewsLambda
      Handler: app.main.handler
      Runtime: python3.11
      MemorySize: 512
      Timeout: 30
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
