name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build FastAPI with AWS SAM
      run: |
        sam build

    - name: Deploy FastAPI to AWS Lambda (Prod)
      run: |
        sam deploy \
          --stack-name CryptoCyberNewsFastAPI \
          --region ${{ secrets.AWS_REGION }} \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --resolve-s3 \
          --parameter-overrides \
            "NewsApiKey=${{ secrets.NEWS_API_KEY }}" \
            "AuthApiKey=${{ secrets.AUTH_API_KEY }}" \
            "StageName=prod"


